language: ruby

rvm:
  - 2.1.5
  - 2.2.1
  - ruby-head

cache: bundler
bundler_args: --jobs=4 --retry=3 --deployment


before_script:
  - mkdir ~/.chef
  - cp .travis/knife.rb ~/.chef/knife.rb
  - cp .travis/test.pem ~/.chef/test.pem
  - cp .travis/database.yml config/database.yml
  - touch log/test.log
  - bundle exec rake db:migrate:reset


script:
  - bundle exec rspec
